### ISSUE TITLE
register with Julia registration bot

### ISSUE THREAD

**Issue by russelljjarvis** [JuliaNeuroscience/SpikeSynchrony.jl#5]
Hi @Datseris, I forked your spike synchrony package and then registered it as a Julia package. I hope you don't mind. The problem is I have another package that uses it as a dependency and its hard to get a julia build to work universally if it contains multiple installs of the ```Pkg.add(url="...")``` kind.

If you want to register it, I could de-register it.

**Comment by Datseris** [comment]
Hi, 
Have you actually worked on the package? I.e., added more features to your fork?

For me the best case scenario would be to actually move the package to some kind of org that cares about these topics.

**Comment by russelljjarvis** [comment]
Yes it would be awesome if there was a Neuroscience Julia org. 

No, I haven't worked on the module, I did write interfacing code (so it can interface with Julia spiking neural network simulator spike train formats (as in I wrangled different spike train formats into formats that can work with this spike synchrony.

It's okay I can un-register it, I just wanted to see if it would make my package build better (I think it did).

If there was a neuroscience Julia org I would definitely join it. Also in an earlier time, I would have started one myself, but I am looking for work atm the moment now though.

**Comment by Datseris** [comment]
> No, I haven't worked on the module

But then it is confusing to me that you'd register a fork instead of asking the original to be registered... I mean, it does not matter that much for me, as I'm happy to transfer the package anyways, but this move doesn't look like good practice, but looks rather weird.

There is clearly a Julia Neuroscience community: 

https://juliapackages.com/c/neuroscience

https://julianeuro.github.io/

the community seems to be coordinated by Alexander Morley: https://github.com/alexmorley 

@alexmorley , are you okay with transfering this package to the Neuro org, and registering it from there?

**Comment by Tokazama** [comment]
https://github.com/JuliaNeuroscience. I would love to have someone else participate in basic PR reviews over there. Kind of hard to know if I'm doing anything helpful for others while talking to the void

**Comment by Datseris** [comment]
I'm confused now... why is there both https://github.com/JuliaNeuroscience and https://github.com/JuliaNeuro  ...? Maybe these two should be merged @Tokazama and @alexmorley ? JuliaNeuroscience has more packages so I'm inclined to move the package there. @Tokazama can you please invite me to the organization and make a team called "SpikeSynchrony" which has access-level rights to this repo, and put me there (and also feel free to put there @russelljjarvis or anyone else that wants to use this package in any way). As soon as you invite me I'll transfer the package.

**Comment by russelljjarvis** [comment]
Hi @Datseris, wow thanks for looking into all of this. I thought you meant a Github Julia-Neuroscience-Organization, not a Julia Neuroscience webpage organization, yes I had noticed those Julia Neuroscience organizations. Perhaps they are all the same on some level, but I can't find GitHub Julia organization web pages.

I think some proportion of the packages on both neuro-organizations, will not build properly with the latest Julia LTS release 1.6.2, that is kind of why I think a Github Julia neuroscience organization is more useful because when you are reading over GitHub packages you can see build status badges and the date of the most recent commit etc.

It seems like you can't easily un-register a package from the general registry, but you can probably update it with a newer release https://discourse.julialang.org/t/remove-package-from-general-registry/71668/2. Let me know if I am wrong.

"@alexmorley , are you okay with transferring this package to the Neuro org, and registering it from there?" -- Would this overwrite my registration (if so good!). If not let me know if there are additional steps I can do to facilitate correcting my spurious package registration.

**Comment by Datseris** [comment]
No, what you said is correct: you cannot unregister a package, now what is done is done. What you can do is do a manual Pull Request to the general registry that changes the github url, git SHA (should be the same actually), and other metadata to the GitHub instance you'd like. This is e.g., something typically done once packages are transferrred to orgs. I've done it many times and so far noone raised any red flags. Just wait until after I move this to JuliaNeuroscience and then you can do the general registry PR.

**Comment by russelljjarvis** [comment]
> "But then it is confusing to me that you'd register a fork instead of asking the original to be registered... I mean, it does not matter that much for me, as I'm happy to transfer the package anyways, but this move doesn't look like good practice, but looks rather weird."  


Yes, I know, I agree I can see that now. The way I was thinking about it was, **A**. I incorrectly assumed the process would be reversible. **B**: I was struggling with package-management breaks as really nothing seemed to work. **C**: I was not sure how responsive you would be (it turns out you are very responsive which is great thanks). **D**. I was not that sure if registering a package, is the same as saying I authored the package, the code providence and authorship history is all on GitHub, and it is un-disputable. I didn't think registering the package would create ambiguity about author credit assignment. The way I was thinking about it was, more like "what can I do to make packages build/install/work"?

Before I erroneously registered the package I also tried to I used `Pkg.add(url="https://github.com/Datseris/SpikeSynchrony.jl")` inside [build/deps.jl](https://github.com/russelljjarvis/SpikeNetOpt.jl/commit/2ec1ec96fb5ded12bdbfb30fabb186baedcb6bef), I believe this approach might work in theory, but I couldn't find the syntax to make ci.yml build from build/deps.jl, thus leading to this sceanario.

I can see that there might be more issues too, like losing control of code quality (like the original code author might want to be the person who says the package is ready). I can see now that the Julia registration bot depends on human etiquette. It can not stop humans from making bad and unconventional decisions.

Anyway. Please accept my apologies, I agree it looks bad, but given the situation, I would like to make amends.

**Comment by russelljjarvis** [comment]
> No, what you said is correct: you cannot unregister a package, now what is done is done. What you can do is do a manual Pull Request to the general registry that changes the github url, git SHA (should be the same actually), and other metadata to the GitHub instance you'd like. This is e.g., something typically done once packages are transferrred to orgs. I've done it many times and so far noone raised any red flags. Just wait until after I move this to JuliaNeuroscience and then you can do the general registry PR.

AOK this is what I will do then! Thanks and also sorry.

**Comment by russelljjarvis** [comment]
> https://github.com/JuliaNeuroscience. I would love to have someone else participate in basic PR reviews over there. Kind of hard to know if I'm doing anything helpful for others while talking to the void

I think what you are doing is useful! I wonder if this organization is also a pure Github Organization too? I will volunteer to participate in PR request reviews (if you think that will be helpful no offense if not, I am still learning Julia). Do you have any links to some outstanding PRs?

**Comment by russelljjarvis** [comment]
> I'm confused now... why is there both https://github.com/JuliaNeuroscience and https://github.com/JuliaNeuro ...? Maybe these two should be merged @Tokazama and @alexmorley ? JuliaNeuroscience has more packages so I'm inclined to move the package there. @Tokazama can you please invite me to the organization and make a team called "SpikeSynchrony" which has access-level rights to this repo, and put me there (and also feel free to put there @russelljjarvis or anyone else that wants to use this package in any way). As soon as you invite me I'll transfer the package.

Is one more neuroimaging scale related, and the other a mixture of mesoscale modelling and neuroimaging? I agree a merge would probably be good. Or a merge combined with shedding of currently un-buildable/un-usable packages.

**Comment by Datseris** [comment]
> I wonder if this organization is also a pure Github Organization too? 

Both orgs we've linked are GitHub organizations. The JuliaNeuro one has a website as one of the repositories of the org. Maybe you want to clarify what you mean with "organization" in the above question? It feels like there is some confusion on the matter.

> Or a merge with a shedding of broken and currently un buildable/un usable packages.

Personally I see no reason to remove anything that hasn't been updated. Maybe at some point someone wants to update them. It has happened in the past with many orgs.

**Comment by russelljjarvis** [comment]
> > I wonder if this organization is also a pure Github Organization too?
> 
> Both orgs we've linked are GitHub organizations. The JuliaNeuro one has a website as one of the repositories of the org. Maybe you want to clarify what you mean with "organization" in the above question? It feels like there is some confusion on the matter.
> 
> > Or a merge with a shedding of broken and currently un buildable/un usable packages.
> 
> Personally I see no reason to remove anything that hasn't been updated. Maybe at some point someone wants to update them. It has happened in the past with many orgs.

You are probably right and there are build status badges on the Julia orgs websites too.

I see now there is a [Github level org](https://github.com/JuliaNeuroscience) that is also a julia-org 

Actually, I am discovering a lot of new stuff. The situation is evolving fast, or I have not been searching effectively, or both.

To clarify my interpretation of different organizations, I just meant, is the organization directly hosted and reflected inside GitHub or not? When it is, you can more easily click to find out the date of the last commit for any particular repository. As a package user this is a useful indicator of how useable a package might be when it is combined with a build badge.

**Comment by Datseris** [comment]
Still sounds like there is some confusion, from the statement "A GitHub level org that is also a julia-org". So, to clarify:

* Every organization we've linked so far is a GitHub organization. It is nothing else than that. A collection of packages under the same banner, hosted entirely on GitHub. They are developed and/or maintained by a specified group of developers: the members of the org. 
* None of these organizations are "officially affiliated with the Julia language".
* The reason each of these organizations has the name "Julia" in their name is because they are composed almost entirely out of _Julia packages_

Furthermore:

> is the organization directly hosted and reflected inside GitHub or not? 

**Everything that can be registered in the Julia General Registry is on GitHub.** Doesn't matter its context.

**Comment by russelljjarvis** [comment]
> 
AOK Thanks for clarifying these points. I have learnt some useful stuff from the discussion above, especially apropos what not what to do with package registration.

I realize that all Julia packages use GitHub to become Julia packages, the contrast I was trying to make was just about the presentation of information on different web pages and how some web pages might better cater to different user needs.

If you compare these two with each other:
example 1 https://julianeuro.github.io/packages
example 2 https://github.com/JuliaNeuroscience/

**Comment by Datseris** [comment]
BTW, can you please link the original PR of the package registration here?

**Comment by russelljjarvis** [comment]
Yes. PR https://github.com/JuliaRegistries/General/pull/51368

**Comment by Datseris** [comment]
I've already made the transfer.

**Comment by russelljjarvis** [comment]
This is great, sorry for consuming your time on this issue. I am glad there is a good resolution!

**Comment by Datseris** [comment]
Just link here the PR that corrects the links in the General Registry when you have it open and we can leave this behind us without much worry :)

**Comment by russelljjarvis** [comment]
AOK, just seeing this now. I will look for the PR that corrects the links in the general Registry. Bare with me...

Everything I can glean about it is here: https://github.com/russelljjarvis/SpikeSynchrony.jl/issues/1

**Comment by Datseris** [comment]
> I will look for the PR 

This doesn't happen automatically, you have to do it...

**Comment by russelljjarvis** [comment]
Oh, I see. I will read about how to trigger it. Oh, hang on. This is in the conversation above right? Above you explain the best path forward. Hang on let me read above.

**Comment by russelljjarvis** [comment]
Found it.

> What you can do is do a manual Pull Request to the general registry that changes the github url, git SHA (should be the same actually), and other metadata to the GitHub instance you'd like. This is e.g., something typically done once packages are transferrred to orgs. I've done it many times and so far noone raised any red flags. Just wait until after I move this to JuliaNeuroscience and then you can do the general registry PR.

This is the new link I will add to the PR:
https://github.com/JuliaNeuroscience/SpikeSynchrony.jl

**Comment by russelljjarvis** [comment]
Unpacking this. I think I should fork the general registry:
https://github.com/JuliaRegistries/General

then do a manual PR to it, which is similar to the one the registration bot made on my behalf, I just replace the link to my fork with https://github.com/JuliaNeuroscience/SpikeSynchrony.jl

**Comment by Datseris** [comment]
yes, you just replace the repo here: https://github.com/JuliaRegistries/General/blob/master/S/SpikeSynchrony/Package.toml#L3

**Comment by russelljjarvis** [comment]
Thanks for that!
I hope this will fix it:
https://github.com/JuliaRegistries/General/pull/51935

Also, I noticed that I did do a minor change to the code that I forgot about. I just changed a single for loop to have the `@inbounds` macro to see if it was faster. If it's a bad change it should be easy to fix. I believe it's a non-breaking change as I used it the code in a few different contexts, but I admit I have not exhaustively tested it.

**Comment by Datseris** [comment]
as long as you run the tests and it didn't break anything then its fine.

**Comment by russelljjarvis** [comment]
Added the proper ".git" suffix. 
https://github.com/JuliaRegistries/General/pull/51935/files#diff-9f173466d557da5313913c5e18c976c96bfa000a5c73a13b0d06fb692ff4c2cd

**Comment by russelljjarvis** [comment]
Now forked from says this:
![forked_from](https://user-images.githubusercontent.com/7786645/148663666-53cc8883-8a06-4284-bdcd-1bb411b67834.png)

Perhaps this means efforts have succeeded?

**Comment by Datseris** [comment]
@russelljjarvis no, it's not fixed. Please try to read carefully and precisely what I'm saying.

I've transfered my repo to the Neuroscience organization. This changes nothing regarding commits. 
Your original fork, from which you tagged a release from, has had additional commits that are different from the original repo that you forked from (mine). Even though you said you didn't do any changes, any kind of commit matters. Look here:

![image](https://user-images.githubusercontent.com/19669089/148675971-6872c107-4d06-47b5-a01f-a37656762639.png)

You see that it says that your master branch and our master branch are completely out of sync? That's because you were doing different kind of commits in the different repos, instead of properly doing a pull request as this the way things should be done.

Now, if you read carefully what user `giordano` said at the general registry PR, you can't change the link of the registered package to the link of the Neuroscience org package, because their git histories are out of sync.

There are two ways to fix this:

1. Do whatever is necessary to make the tagged commit of your fork be the current last commit of Neuroscience/SpikeSynchrony.jl
2. Ask the people that run the General Registry to **delete your registration**, so we can tag a new release from the correct repo.

**Comment by russelljjarvis** [comment]
> 
1. Do whatever is necessary to make the tagged commit of your fork be the current last commit of Neuroscience/SpikeSynchrony.jl

> 
2. Ask the people that run the General Registry to delete your registration, so we can tag a new release from the correct repo.

I tried a bit of 1, but to be safe I might try 2 at this point. I will ask giordano in the second conversation at the registry to delete my registration.


For 1. I just did:

```
git clone https://github.com/JuliaNeuroscience/SpikeSynchrony.jl
cd SpikeSynchrony.jl
```
```
git remote add me https://github.com/russelljjarvis/SpikeSynchrony.jl
```
And then
```git push --force me master```
The tricky part is the tag. I don't know if issuing will 
``` git tag -a v0.1.0 -m "Description: Julia implementations for measuring distances, synchrony and correlation between spike trains"```                                        
```git push origin v0.1.0```
have the intended effect or if it will do something else.

**Comment by Datseris** [comment]
The git hash is already registered in the general registry. **It is useless to attempt any change in your fork**, because its history is saved in the Registry already. The only way forwards is to make the necessary change in this original repo. I guess only I can do this as I need to force push current master branch.

**Comment by russelljjarvis** [comment]
Ok I will wait for you to do that.

**Comment by Datseris** [comment]
okay this is resolved now, i've also tagged version 0.1.1 which is current `master` branch to ensure things work.

**Comment by russelljjarvis** [comment]
Phew! Thanks and also sorry. Rest assured I won't intervene in anything SpikeSynchrony.jl unless you ask me to or without your explicit permission henceforth.

**Comment by Datseris** [comment]
just do pull requests for any feature you want, it's almost certain they will be merged instantly.

**Comment by Tokazama** [comment]
If you want a set of guidelines to follow for collaborating you might be interested in https://github.com/SciML/ColPracf

**Comment by russelljjarvis** [comment]
Reading it now. I think the 'f' on the end of ColPracf is a typo but I believe this is the correct document:
https://github.com/SciML/ColPrac#readme

It is really specific which is good.

**Comment by Tokazama** [comment]
😆 sorry, I'm clearly doing too many things at once.
